### ISSUE TITLE
If Statement checks if pointer is nullptr but should check if value of pointer is 0

### ISSUE THREAD

**Issue by fabch1** [kkAyataka/plusaes#1]
The if statement in decrypt_ecb, decrypt_cbc checks if the pointer is a nullptr, but the comments say it checks if the value is 0.
`if (padded_size) {
`
should be 
`if (*padded_size){
`
The changes will affect lines 403, 520, 656

**Comment by kkAyataka** [comment]
I'm using 0 and nullptr in the same meaning in the comments.

But I think that the current comment is ambiguous. I will consider adjustment the comment.
