### ISSUE TITLE
How do I use this though

### ISSUE THREAD

**Issue by Xyncgas** [kkAyataka/plusaes#10]

**Comment by Xyncgas** [comment]
Can you add some documentations please

**Comment by Xyncgas** [comment]
I mean I figured out by reading AES standard and understanding which files to include.
basically I just #include "plusaes/plusaes.hpp"
and use encrypt_cbc/decrypt_cbc something like that right
I mean first of all thanks for your amazing codes
and if you can explain some more it would be awesome too

**Comment by kkAyataka** [comment]
Thank you.

I also think the documentation is poor. I consider writing a documentation about simple usage in the README.

**Comment by kkAyataka** [comment]
- I write a usage sample in the README.md
- I publish API documents in the GitHub Pages

**Comment by Xyncgas** [comment]
I havent looked at it yet

**Comment by Xyncgas** [comment]
but I am so excited, it empowers me to do so much things, with a header only library, thanks, for lending power to me

**Comment by Xyncgas** [comment]
padded_size = 0, because it can just be 0 or, has to manually calculate and keep track of and be different every time ?

**Comment by kkAyataka** [comment]
- This library uses PKCS#7 padding
- If you want to use other padding algorithm, you can disable padding setting
    - Set false to pads and set 0 to padded_size
- 0 is not used as padding data on the PKCS#7
    - If the data size is multiple by 16, padding data is 16 (1 block is padded with 16)

Is that what you asked?

**Comment by Xyncgas** [comment]
I think for now I don't know, but your information is useful, I will try to ask again when I am in doubt too
