### ISSUE TITLE
unnamed class used in typedef name cannot declare members other than non-static data members, member enumerations, or member classes

### ISSUE THREAD

**Issue by BullyWiiPlaza** [kkAyataka/plusaes#15]
Using ```C++20``` in ```Visual Studio 2019``` I'm getting a compilation error:

```
unnamed class used in typedef name cannot declare members other than non-static data members, member enumerations, or member classes
```

It is referring to this piece of code:
```
typedef struct {
	Word w[4];
	Word& operator[](const int index) {
		return w[index];
	}
	const Word& operator[](const int index) const {
		return w[index];
	}
} State;
```

It seems like the fix is easily applied as follows:
```
struct State {
	Word w[4];
	Word& operator[](const int index) {
		return w[index];
	}
	const Word& operator[](const int index) const {
		return w[index];
	}
};
```
Now it compiles. I didn't test any other compilers or language versions.

What do you think about this?

**Comment by kkAyataka** [comment]
Thank you.

Probably I will adopt your code. But I would like to check other environments.

**Comment by kkAyataka** [comment]
- Visual Studio 2019 /std:c++14: warning C5208
- Visual Studio 2019 /std:c++latest: error C7626
