### ISSUE TITLE
Exceptions/Code is not compliant with C++17

### ISSUE THREAD

**Issue by Mr-Rayman** [kkAyataka/plusaes#2]
C++17 removed dynamic exception specifications / throw. Before that, they had been deprecated since C++11. 

GCC 7.3.0 in C++17 Mode reports these errors:

plusaes.hpp:197:57: error: ISO C++1z does not allow dynamic exception specifications
 inline unsigned int get_round_count(const int key_size) throw(std::invalid_argument) {
                                                         
plusaes.hpp:210:75: error: ISO C++1z does not allow dynamic exception specifications
 inline RoundKeys expand_key(const unsigned char *key, const int key_size) throw(std::invalid_argument) {

**Comment by kkAyataka** [comment]
Thank you for your report.

I checked C++17 specifications and I understood that (dynamic) exception specifications was removed.

I want to consider about C++17 support.

**Comment by Mr-Rayman** [comment]
Thank you very much for your fast response/fix!
