### ISSUE TITLE
Relax GCM restriction related to IV size

### ISSUE THREAD

**Issue by Alkenso** [kkAyataka/plusaes#31]
In some cases there is a need to use GCM with IV of size 0.

I'd like to propose to remove 
```
if (iv_size < 1) {
    return kErrorInvalidIvSize;
}
```
from `check_gcm_cond` function

**Comment by kkAyataka** [comment]
I considered 0-size IV, but it is hard to accept.

My understanding is that the IV size of GCM should be one or more. The library can arithmetically calculate with 0-size IV. But, the algorithm behavior seems to be very different.

**Comment by Alkenso** [comment]
Agree, that could be strange situation. But in some cases there is need to omit IV (seen in some encryption mechanisms of Apple)

**Comment by kkAyataka** [comment]
Hmm. I cannot imagine. I don't want to ignore the specifications. Can you give a specific use case?

For example, If I create a special version of the following, would It help you?

```cpp
Error encrypt_gcm_no_iv();
```

**Comment by Alkenso** [comment]
any case that allows use GCM with no IV would be appreciated!
want to use your shiny lib without custom modifications =)
