### ISSUE TITLE
Different encryption result with plusaes and openssl for AES-256-GCM 

### ISSUE THREAD

**Issue by purushottam-p** [kkAyataka/plusaes#45]
I am trying to use plusaes library on a client-server system where the server uses OpenSSL for encryption and decryption.
I am getting different encrypted data with plusaes and OpenSSL for the same key, IV and data.
In OpenSSL, I am first making a `EVP_CIPHER_CTX` with the key and IV and then using it for encryption. With that and the same data I am getting the result as : ```0x1c 0xf0 0x9a 0xad 0xae 0xa4 0x56 0xfc 0x3a 0x16 0xae 0x92 0xde 0xed 0xbc 0x9a 0xcd 0xda 0xd8 0x5d 0xbf 0x89 0x22 0xfb ```

whereas with plusaes, the result is ``` 0x2d 0xea 0x4a 0x31 0x42 0x62 0xc4 0x07 0x80 0x5b 0xaf 0x4b 0x90 0x88 0x67 0x14 0x68 0x4d 0xd7 0xbb 0xaa 0xcd 0x1f 0x37```

 

```
#include "plusaes/plusaes.hpp"

#include <string>
#include <vector>

#include <iostream>
#include <iomanip>

void print_bytes(unsigned char *data, int n){
    for (int i = 0; i < n; i++) {
        std::cout << "0x" << std::setw(2) << std::setfill('0') << std::hex << static_cast<int>(data[i]) << " ";
    }
    std::cout << std::dec << std::endl; // Restore the default decimal formatting
}

int main() {
    int bytes = 24;
    unsigned char data[] = {
        0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F,
        0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07,
        0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F,
    };


    const unsigned char key[] = {
        0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07,
        0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F,
        0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07,
        0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F,
    };
    
    const unsigned char iv[] = {
        0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07,
        0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F,
    };

    //encrypt
    const unsigned char* aadata;
    unsigned char *tag;
    tag = (unsigned char*)malloc(16);
    plusaes::Error err = plusaes::encrypt_gcm(data, sizeof(data), aadata, 0, key, sizeof(key), iv, sizeof(iv), tag, 16);

    if(err != plusaes::kErrorOk){
        std::cout << "encryption failed \n";
    }
    else{
        std::cout << "encryption successful \n";
    }
    unsigned char *enc;
    enc = (unsigned char*)malloc(2*bytes);
    memcpy(enc, data, bytes);

    //print enc bytes and tag
    std::cout << "enc bytes are : " << std::endl;
    print_bytes(enc, bytes);

    /*
    output : 
    0x2d 0xea 0x4a 0x31 0x42 0x62 0xc4 0x07 0x80 0x5b 0xaf 0x4b 0x90 0x88 0x67 0x14 0x68 0x4d 0xd7 0xbb 0xaa 0xcd 0x1f 0x37
    
    */
}
```

**Comment by purushottam-p** [comment]
solved

**Comment by TheOnlyJoey** [comment]
@purushottam-p Any hints on how you fixed this? I am having a similar issue, but decrypting with tag mismatches between Node.js Crypto (which uses openssl in the back) and plusaes (see #48 for more reference). Even with CTR (crypt_ctr) i find that it does not decrypt openssl payloads...

**Comment by purushottam-p** [comment]
OpenSSl takes the first 12 bytes of the iv that you provide and appends counter(0x00 0x00 0x00 0x01) of 4 bytes to it (using  EVP_EncryptInit_ex(...)). Whereas plusaes asks you the size of your iv `inline Block calc_J0(const Block & H, const unsigned char * iv, const std::size_t iv_size)`. My issue was solved when i passed the iv_size as 12 explicitly. I didn't compare tags.
