### ISSUE TITLE
CBC encryption message length minimum?

### ISSUE THREAD

**Issue by dstoker-cricut** [kkAyataka/plusaes#5]
Great job on the library! It has been working well for us. I did find an oddity, though. ECB mode encryption works with messages of any length, but CBC mode requires that the messages be >= 17 bytes in order for the decryption to succeed. I have tried this on > 150,000 messages. Is this a known issue?

**Comment by dstoker-cricut** [comment]
I can submit code samples and such as needed. If any clarification or code is required then please let me know.

**Comment by kkAyataka** [comment]
Thank you for your report.

I analyzed the code. I found bug in the first block encryption of the CBC logic when the data size is less than 16. 

I'm considering fix.

**Comment by kkAyataka** [comment]
I fixed this issue. Try it if you like

**Comment by dstoker-cricut** [comment]
Ran it through several thousand tests and it looks good! Thanks for the help.

**Comment by kkAyataka** [comment]
Thank you!
